#!/bin/bash
cd $LARAVEL_PATH_CONTAINER
composer install --prefer-dist --no-interaction --optimize-autoloader --no-dev
php artisan migrate
php artisan db:seed
php artisan generate_admin_account admin 123456 admin@gmail.com
# cache Optimizing ...